#!/usr/bin/env python
import sys

def printError(str):
	print('\033[91m' + str + '\033[0m', file=sys.stderr)

def processFile(file, infile):
	allocs = {}
	linenum = 0
	for line in infile:
		linenum += 1
		parts = line.strip().split(' ')
		if len(parts) != 4 or (parts[0] != 'A' and parts[0] != 'F'):
			printError('Line ' + str(linenum) + ': invalid format')
			continue

		key = parts[1] + ' ' + parts[2]
		if parts[0] == 'A':
			if key in allocs:
				print('Line ' + str(linenum) + ': repeated alloc: ' + key + ' ' + parts[3]);
				continue
			allocs[key] = parts[3]
		else:
			if not key in allocs:
				print('Line ' + str(linenum) + ': free before alloc: ' + key + ' ' + parts[3]);
				continue
			del allocs[key]

	if allocs:
		print('Remaining:')
		for key,comment in allocs.items():
			print('\t' + key + ' ' + comment)

if len(sys.argv) < 2:
	print('Usage: ' + sys.argv[0] + ' <trace.txt file>', file=sys.stderr)
	sys.exit(1)
if len(sys.argv) > 2:
	printError('Too many arguments')
	sys.exit(1)

ret = 0
try:
	with open(sys.argv[1], 'r') as infile:
		processFile(sys.argv[1], infile)
except OSError as e:
	printError(sys.argv[1] + ': ' + e.strerror)
	ret = 1
sys.exit(ret)
